In [24]:
import pandas as pd
import numpy as np
data=pd.DataFrame([[12,3.7,16],[15,np.nan,np.nan],[13,4.7,18],[17,7.2,np.nan],[12,3.7,16]])
data

    0    1     2
0  12  3.7  16.0
1  15  NaN   NaN
2  13  4.7  18.0
3  17  7.2   NaN
4  12  3.7  16.0

In [25]:
data1=data.dropna()
data1

    0    1     2
0  12  3.7  16.0
2  13  4.7  18.0
4  12  3.7  16.0

In [26]:
data.fillna(3)

    0    1     2
0  12  3.7  16.0
1  15  3.0   3.0
2  13  4.7  18.0
3  17  7.2   3.0
4  12  3.7  16.0

In [27]:
data3=data.interpolate()
data3

    0    1     2
0  12  3.7  16.0
1  15  4.2  17.0
2  13  4.7  18.0
3  17  7.2  17.0
4  12  3.7  16.0

In [22]:
data3.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [23]:
data3.drop_duplicates()

    0    1     2
0  12  3.7  16.0
1  15  4.2  12.0
2  13  4.7  18.0
3  17  7.2  17.0