In [9]:
import pandas as pd

data=pd.DataFrame([[1.,6.5,3.],[1.,None,None],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data.isna()

       0      1      2
0  False  False  False
1  False   True   True
2   True   True   True
3   True  False  False

In [10]:
data1=data.dropna()

In [11]:
data1.isna().sum()

0    0
1    0
2    0
dtype: int64

In [12]:
data2=data.fillna(1)

In [13]:
data2

     0    1    2
0  1.0  6.5  3.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  6.5  3.0

In [14]:
import pandas as pd
import numpy as np
df=pd.DataFrame([[7,8,11],[5.6,8,9],[np.nan,8,12],[13,np.nan,np.nan]])
df

      0    1     2
0   7.0  8.0  11.0
1   5.6  8.0   9.0
2   NaN  8.0  12.0
3  13.0  NaN   NaN

In [15]:
data3=df.interpolate()

In [16]:
data3

      0    1     2
0   7.0  8.0  11.0
1   5.6  8.0   9.0
2   9.3  8.0  12.0
3  13.0  8.0  12.0