In [8]:
import pandas as pd
import numpy as np
data=pd.DataFrame([[10,7.8,12],[11,6.8,14],[12,np.nan,15],[np.nan,14,20]])
data

      0     1   2
0  10.0   7.8  12
1  11.0   6.8  14
2  12.0   NaN  15
3   NaN  14.0  20

In [10]:
data.isna().sum()

0    1
1    1
2    0
dtype: int64

In [11]:
data.dropna()

      0    1   2
0  10.0  7.8  12
1  11.0  6.8  14

In [12]:
data1=data.fillna(3)
data1

      0     1   2
0  10.0   7.8  12
1  11.0   6.8  14
2  12.0   3.0  15
3   3.0  14.0  20

In [13]:
data1.isna().sum()

0    0
1    0
2    0
dtype: int64