In [1]:
import pandas as pd
data={
    "Scores":[55,41,78,65,87,95,65,36,61,84],
    "Sample Papers practised":[3,1,4,5,4,5,6,4,None,5],
    "Sample Papers Average":[57,38,73,68,79,83,62,None,57,80],
    "Class Attendance":[12,6,13,13,11,11,13,3,10,14]
}
df=pd.DataFrame(data)
df.to_csv("Performance_Analysis")
print(df)

   Scores  Sample Papers practised  Sample Papers Average  Class Attendance
0      55                      3.0                   57.0                12
1      41                      1.0                   38.0                 6
2      78                      4.0                   73.0                13
3      65                      5.0                   68.0                13
4      87                      4.0                   79.0                11
5      95                      5.0                   83.0                11
6      65                      6.0                   62.0                13
7      36                      4.0                    NaN                 3
8      61                      NaN                   57.0                10
9      84                      5.0                   80.0                14

In [2]:
df=pd.read_csv("Performance_Analysis")
data1=df.drop("Class Attendance",inplace=False,axis=1)
print(data1)

   Unnamed: 0  Scores  Sample Papers practised  Sample Papers Average
0           0      55                      3.0                   57.0
1           1      41                      1.0                   38.0
2           2      78                      4.0                   73.0
3           3      65                      5.0                   68.0
4           4      87                      4.0                   79.0
5           5      95                      5.0                   83.0
6           6      65                      6.0                   62.0
7           7      36                      4.0                    NaN
8           8      61                      NaN                   57.0
9           9      84                      5.0                   80.0

In [3]:
df.set_index("Scores")
df.drop("Unnamed: 0",inplace=False,axis=1)

   Scores  Sample Papers practised  Sample Papers Average  Class Attendance
0      55                      3.0                   57.0                12
1      41                      1.0                   38.0                 6
2      78                      4.0                   73.0                13
3      65                      5.0                   68.0                13
4      87                      4.0                   79.0                11
5      95                      5.0                   83.0                11
6      65                      6.0                   62.0                13
7      36                      4.0                    NaN                 3
8      61                      NaN                   57.0                10
9      84                      5.0                   80.0                14

In [4]:
df=pd.read_csv("Performance_Analysis")
new1=(range(1,11))
df.reindex(new1)

,Unnamed: 0,Scores,Sample Papers practised,Sample Papers Average,Class Attendance
1,1.0,41.0,1.0,38.0,6.0
2,2.0,78.0,4.0,73.0,13.0
3,3.0,65.0,5.0,68.0,13.0
4,4.0,87.0,4.0,79.0,11.0
5,5.0,95.0,5.0,83.0,11.0
6,6.0,65.0,6.0,62.0,13.0
7,7.0,36.0,4.0,NaN,3.0
8,8.0,61.0,NaN,57.0,10.0
9,9.0,84.0,5.0,80.0,14.0
10,NaN,NaN,NaN,NaN,NaN

In [5]:
f=pd.read_csv("Performance_Analysis")
new2=df.sort_values(by='Scores',inplace=False,kind="quicksort",na_position='last',ascending=False)
print(new2)

   Unnamed: 0  Scores  Sample Papers practised  Sample Papers Average  \
5           5      95                      5.0                   83.0
4           4      87                      4.0                   79.0
9           9      84                      5.0                   80.0
2           2      78                      4.0                   73.0
3           3      65                      5.0                   68.0
6           6      65                      6.0                   62.0
8           8      61                      NaN                   57.0
0           0      55                      3.0                   57.0
1           1      41                      1.0                   38.0
7           7      36                      4.0                    NaN

   Class Attendance
5                11
4                11
9                14
2                13
3                13
6                13
8                10
0                12
1                 6
7                 3