In [4]:
import pandas as pd
data={
    "Hours Studied":[7,4,8,5,7,6,5,6,7,8],
    "Exam Scores":[99,43,83,61,74,68,62,59,69,84],
    "Extracurricular Activities":["Yes","Yes","No","Yes","No","Yes","Yes","Yes","No","Yes"],
    "Sleep Hours":[6,7,6,7,7,7,6,8,7,6],
    "Sample Question Papers practised":[7,2,5,4,5,5,4,3,4,6],
    "Sample Paper's Average Result":[91,38,77,55,65,60,58,54,60,80]
}
df=pd.DataFrame(data)
print("Dataset Preview:")
print(df)
df.to_csv("Student_Performance.csv")

Dataset Preview:
   Hours Studied  Exam Scores Extracurricular Activities  Sleep Hours  \
0              7           99                        Yes            6
1              4           43                        Yes            7
2              8           83                         No            6
3              5           61                        Yes            7
4              7           74                         No            7
5              6           68                        Yes            7
6              5           62                        Yes            6
7              6           59                        Yes            8
8              7           69                         No            7
9              8           84                        Yes            6

   Sample Question Papers practised  Sample Paper's Average Result
0                                 7                             91
1                                 2                             38
2                                 5                             77
3                                 4                             55
4                                 5                             65
5                                 5                             60
6                                 4                             58
7                                 3                             54
8                                 4                             60
9                                 6                             80

In [5]:
df=pd.read_csv("Student_Performance.csv")
data1=df[["Exam Scores","Hours Studied"]]
print(data1)

   Exam Scores  Hours Studied
0           99              7
1           43              4
2           83              8
3           61              5
4           74              7
5           68              6
6           62              5
7           59              6
8           69              7
9           84              8

In [6]:
df.shape

(10, 7)

In [7]:
df.columns

Index(['Unnamed: 0', 'Hours Studied', 'Exam Scores',
       'Extracurricular Activities', 'Sleep Hours',
       'Sample Question Papers practised', 'Sample Paper's Average Result'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        10 non-null     int64
 1   Hours Studied                     10 non-null     int64
 2   Exam Scores                       10 non-null     int64
 3   Extracurricular Activities        10 non-null     str
 4   Sleep Hours                       10 non-null     int64
 5   Sample Question Papers practised  10 non-null     int64
 6   Sample Paper's Average Result     10 non-null     int64
dtypes: int64(6), str(1)
memory usage: 692.0 bytes

In [12]:
df.tail()

,Unnamed: 0,Hours Studied,Exam Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers practised,Sample Paper's Average Result
5,5,6,68,Yes,7,5,60
6,6,5,62,Yes,6,4,58
7,7,6,59,Yes,8,3,54
8,8,7,69,No,7,4,60
9,9,8,84,Yes,6,6,80

In [13]:
df=pd.read_csv("Student_Performance.csv")
data2=df[["Exam Scores","Hours Studied"]]
print(data2)

   Exam Scores  Hours Studied
0           99              7
1           43              4
2           83              8
3           61              5
4           74              7
5           68              6
6           62              5
7           59              6
8           69              7
9           84              8

In [16]:
import numpy as np
import pandas as pd
data=np.array([(22,56,89),(41,59,63),(70,80,90)])
              
dtarra=pd.DataFrame(data)
dtarra

    0   1   2
0  22  56  89
1  41  59  63
2  70  80  90